### ISSUE TITLE
propose logo

### ISSUE THREAD

**Issue by dee-y** [TobiTenno/QuickMute#1]
Hello @TobiTenno  i am a graphic designer. I would like to know if you would be interested in me making a logo for this project. If you would have me, i would make a logo for you, and it's free.

**Comment by TobiTenno** [comment]
I appreciate it, If you'd like to throw some at me. this is mostly a side project that doesn't get a ton of work from me. If you're interested, I'll take a look what you can make.

**Comment by dee-y** [comment]
Hi @TobiTenno, i have designed this logo. Fast symbol as antenna on the head of the bot, then the mute symbol, hence QuickMute. Any ideas?

![quickmute-01](https://user-images.githubusercontent.com/36637989/42069114-cfb05bea-7b47-11e8-9607-90ed57b776c6.png)

**Comment by TobiTenno** [comment]
It's definitely interesting. Right now, due to it being deployed per-guild, the icon is usually customized on the server, but for the project itself, it's nice

**Comment by dee-y** [comment]
Am glad you think it suits the project...here is another version without the messy teeth...
![quickmute-01](https://user-images.githubusercontent.com/36637989/42106052-8c185030-7bca-11e8-84d9-ff79c3d90782.png)

any preferences between the two? can i go ahead and make a pull request?

**Comment by TobiTenno** [comment]
I prefer the second. I look forward to seeing the PR.

**Comment by dee-y** [comment]
Hi @TobiTenno, i have exported all necessary files in editable formats and uploaded them at google drive here https://drive.google.com/drive/folders/1VlX7AzU6TLNvxyqdR4AItY8Pgy1hPXo0?usp=sharing

i have also made the pull request with logo files inside the images folder here https://github.com/TobiTenno/QuickMute/pull/2

Best regards,
Dee-y.

**Comment by dee-y** [comment]
Great!, can't wait to see how it fits in with the github page.
